using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Velora.Application.Administration;
using Velora.Domain.Administration;
using Velora.Domain.Commerce;
using Velora.Infrastructure.Persistence;

namespace Velora.Infrastructure.Commerce;

internal sealed class AdminCommerceService(ApplicationDbContext context) : IAdminCommerceService
{
    public async Task<AdminDashboardStats> GetDashboardAsync(CancellationToken cancellationToken = default)
    {
        var recent = await GetOrdersAsync(null, 1, 8, cancellationToken); var closed = new[] { OrderStatus.Delivered, OrderStatus.Cancelled };
        return new AdminDashboardStats(await context.Products.CountAsync(x => x.IsActive && !x.IsArchived, cancellationToken), await context.ProductVariants.CountAsync(x => x.IsActive && x.StockQuantity <= x.LowStockThreshold, cancellationToken), await context.Users.CountAsync(x => x.IsActive, cancellationToken), await context.Orders.CountAsync(x => !closed.Contains(x.Status), cancellationToken), await context.Orders.Where(x => x.Status != OrderStatus.Cancelled).SumAsync(x => (decimal?)x.Total, cancellationToken) ?? 0m, recent);
    }
    public async Task<IReadOnlyList<AdminOrderListItem>> GetOrdersAsync(string? status, int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var query = context.Orders.AsNoTracking(); if (Enum.TryParse<OrderStatus>(status, true, out var parsed)) query = query.Where(x => x.Status == parsed);
        return await query.OrderByDescending(x => x.CreatedAtUtc).Skip((Math.Max(1, page) - 1) * pageSize).Take(pageSize).Select(x => new AdminOrderListItem(x.Id, x.Number, x.CustomerEmail, x.Status.ToString(), x.Total, x.Currency, x.Items.Sum(i => i.Quantity), x.CreatedAtUtc)).ToListAsync(cancellationToken);
    }
    public Task<AdminOrderDetails?> GetOrderAsync(Guid id, CancellationToken cancellationToken = default) => context.Orders.AsNoTracking().Where(x => x.Id == id).Select(x => new AdminOrderDetails(x.Id, x.Number, x.CustomerEmail, x.RecipientName, x.PhoneNumber, x.AddressLine1 + ", " + x.City + ", " + x.CountryCode, x.Status.ToString(), x.Payments.OrderByDescending(p => p.CreatedAtUtc).Select(p => p.Status.ToString()).FirstOrDefault() ?? "Pending", x.Shipments.Select(s => s.Status.ToString()).FirstOrDefault() ?? "Pending", x.Total, x.Currency, x.CreatedAtUtc, x.Items.Select(i => new AdminOrderLine(i.ProductName, i.Sku, i.Option, i.Quantity, i.LineTotal)).ToList(), x.StatusHistory.OrderByDescending(h => h.CreatedAtUtc).Select(h => h.CreatedAtUtc.ToString("u") + " — " + h.Status + ": " + h.Note).ToList())).FirstOrDefaultAsync(cancellationToken);
    public async Task UpdateOrderAsync(Guid id, string status, string shipmentStatus, string note, Guid actorId, string ipAddress, CancellationToken cancellationToken = default)
    {
        var order = await context.Orders.Include(x => x.Shipments).Include(x => x.Payments).FirstOrDefaultAsync(x => x.Id == id, cancellationToken) ?? throw new InvalidOperationException("Order not found.");
        if (!Enum.TryParse<OrderStatus>(status, true, out var nextStatus)) throw new InvalidOperationException("Invalid order status."); order.Status = nextStatus; order.UpdatedAtUtc = DateTime.UtcNow;
        var shipment = order.Shipments.FirstOrDefault(); if (shipment is not null && Enum.TryParse<ShipmentStatus>(shipmentStatus, true, out var nextShipment)) { shipment.Status = nextShipment; if (nextShipment == ShipmentStatus.Shipped) shipment.ShippedAtUtc ??= DateTime.UtcNow; if (nextShipment == ShipmentStatus.Delivered) shipment.DeliveredAtUtc ??= DateTime.UtcNow; }
        var payment = order.Payments.OrderByDescending(x => x.CreatedAtUtc).FirstOrDefault(); if (payment is not null && nextStatus == OrderStatus.Delivered) { payment.Status = PaymentStatus.Paid; payment.PaidAtUtc ??= DateTime.UtcNow; }
        order.StatusHistory.Add(new OrderStatusHistory { Id = Guid.NewGuid(), Status = nextStatus, Note = note.Trim(), ChangedByUserId = actorId }); Audit("Order.StatusChanged", nameof(Order), id.ToString(), actorId, ipAddress, new { status, shipmentStatus }); await context.SaveChangesAsync(cancellationToken);
    }
    public async Task<IReadOnlyList<AdminCouponModel>> GetCouponsAsync(CancellationToken cancellationToken = default) => await context.DiscountCoupons.AsNoTracking().Where(x => !x.IsArchived).OrderByDescending(x => x.StartsAtUtc).Select(x => new AdminCouponModel { Id = x.Id, Code = x.Code, Type = x.Type.ToString(), Value = x.Value, MinimumOrderAmount = x.MinimumOrderAmount, UsageLimit = x.UsageLimit, UsageCount = x.UsageCount, StartsAtUtc = x.StartsAtUtc, EndsAtUtc = x.EndsAtUtc, IsActive = x.IsActive }).ToListAsync(cancellationToken);
    public Task<AdminCouponModel?> GetCouponAsync(Guid id, CancellationToken cancellationToken = default) => context.DiscountCoupons.AsNoTracking().Where(x => x.Id == id).Select(x => new AdminCouponModel { Id = x.Id, Code = x.Code, Type = x.Type.ToString(), Value = x.Value, MinimumOrderAmount = x.MinimumOrderAmount, UsageLimit = x.UsageLimit, UsageCount = x.UsageCount, StartsAtUtc = x.StartsAtUtc, EndsAtUtc = x.EndsAtUtc, IsActive = x.IsActive }).FirstOrDefaultAsync(cancellationToken);
    public async Task<Guid> SaveCouponAsync(AdminCouponModel model, Guid actorId, string ipAddress, CancellationToken cancellationToken = default) { var coupon = model.Id is null ? new DiscountCoupon { Id = Guid.NewGuid() } : await context.DiscountCoupons.FindAsync([model.Id.Value], cancellationToken) ?? throw new InvalidOperationException("Coupon not found."); if (model.Id is null) context.DiscountCoupons.Add(coupon); coupon.Code = model.Code.Trim().ToUpperInvariant(); coupon.Type = Enum.Parse<DiscountType>(model.Type, true); coupon.Value = model.Value; coupon.MinimumOrderAmount = model.MinimumOrderAmount; coupon.UsageLimit = model.UsageLimit; coupon.StartsAtUtc = model.StartsAtUtc; coupon.EndsAtUtc = model.EndsAtUtc; coupon.IsActive = model.IsActive; Audit(model.Id is null ? "Coupon.Created" : "Coupon.Updated", nameof(DiscountCoupon), coupon.Id.ToString(), actorId, ipAddress, new { coupon.Code }); await context.SaveChangesAsync(cancellationToken); return coupon.Id; }
    public async Task ArchiveCouponAsync(Guid id, Guid actorId, string ipAddress, CancellationToken cancellationToken = default) { var coupon = await context.DiscountCoupons.FindAsync([id], cancellationToken) ?? throw new InvalidOperationException("Coupon not found."); coupon.IsArchived = true; coupon.IsActive = false; Audit("Coupon.Archived", nameof(DiscountCoupon), id.ToString(), actorId, ipAddress, null); await context.SaveChangesAsync(cancellationToken); }
    public async Task<IReadOnlyList<AdminAuditItem>> GetAuditAsync(int page, int pageSize, CancellationToken cancellationToken = default) => await context.AuditLogs.AsNoTracking().OrderByDescending(x => x.CreatedAtUtc).Skip((Math.Max(1, page) - 1) * pageSize).Take(pageSize).Select(x => new AdminAuditItem(x.Action, x.EntityName, x.EntityId, x.DetailsJson, x.IpAddress, x.CreatedAtUtc, x.UserId)).ToListAsync(cancellationToken);
    public async Task RecordAuditAsync(string action, string entity, string entityId, Guid actorId, string ipAddress, object? details, CancellationToken cancellationToken = default) { Audit(action, entity, entityId, actorId, ipAddress, details); await context.SaveChangesAsync(cancellationToken); }
    private void Audit(string action, string entity, string id, Guid actorId, string ipAddress, object? details) => context.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), UserId = actorId, Action = action, EntityName = entity, EntityId = id, IpAddress = ipAddress, DetailsJson = details is null ? string.Empty : JsonSerializer.Serialize(details) });
}
